# Generated by Django 5.2.17 on 2026-08-17 14:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

from common.rls import enable_rls

# Databases that db/setup-local.sh never touched — the test database above all — must
# converge on the same grants: every table rcp_owner creates from here on is usable by
# rcp_app automatically, and anything created before this migration (Django's own apps)
# is caught up. Idempotent, and later append-only REVOKEs run after this, so they stick.
BOOTSTRAP_GRANTS = """\
ALTER DEFAULT PRIVILEGES FOR ROLE rcp_owner IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rcp_app;
ALTER DEFAULT PRIVILEGES FOR ROLE rcp_owner IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO rcp_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO rcp_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO rcp_app;
"""

# The login crossing (ADR 0014). The user table is under forced RLS, so authenticating
# needs one narrow path across the boundary: a SECURITY DEFINER function owned by
# rcp_login (BYPASSRLS, NOLOGIN, created by db/setup-local.sh) returning exactly what a
# credential check needs. rcp_owner can hand the function over because setup-local.sh
# makes it a member of rcp_login — membership does not confer BYPASSRLS.
LOGIN_LOOKUP = """\
DO $do$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rcp_login') THEN
        RAISE EXCEPTION 'role rcp_login does not exist -- run db/setup-local.sh first';
    END IF;
END
$do$;

CREATE FUNCTION login_lookup(uname text)
RETURNS TABLE (user_id uuid, pw_hash text, organization_id uuid)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $fn$
    SELECT id, pw_hash::text, organization_id
    FROM app_user
    WHERE username = uname AND is_active
$fn$;

GRANT SELECT ON app_user TO rcp_login;
-- Taking ownership requires CREATE on the schema, which rcp_login should not keep.
GRANT CREATE ON SCHEMA public TO rcp_login;
ALTER FUNCTION login_lookup(text) OWNER TO rcp_login;
REVOKE CREATE ON SCHEMA public FROM rcp_login;
REVOKE ALL ON FUNCTION login_lookup(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION login_lookup(text) TO rcp_app;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunSQL(BOOTSTRAP_GRANTS, migrations.RunSQL.noop),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("wordmark", models.CharField(blank=True, default="", max_length=200)),
                ("place", models.CharField(blank=True, default="", max_length=200)),
                (
                    "ai_notice_template",
                    models.TextField(
                        default="Software was used to assess you. Every finding recorded about you cites the passage it was read from, and you can see both."
                    ),
                ),
            ],
            options={
                "db_table": "organization",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password", models.CharField(db_column="pw_hash", max_length=128)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "app_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        enable_rls("app_user"),
        migrations.RunSQL(LOGIN_LOOKUP, "DROP FUNCTION IF EXISTS login_lookup(text);"),
    ]
