# Generated by Django 5.2.17 on 2026-08-25 12:44, then hand-merged from a two-file split
# (channels is a new app in the same generation pass, which defers cross-app FKs to a
# second migration) and extended with the ADR 0012 trigger and RLS.

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import common.models
from common.rls import enable_rls

# Invariant 1's attach gate, reusing the function the searches migration defined: nothing
# attaches to a role that is not open. The function already exists in the database by the
# time this migration runs (searches is a dependency below); this just points a second
# trigger at it.
CANDIDACY_ROLE_MUST_BE_OPEN = """\
CREATE TRIGGER candidacy_role_must_be_open
    BEFORE INSERT ON candidacy
    FOR EACH ROW EXECUTE FUNCTION role_must_be_open();
"""

CANDIDACY_ROLE_MUST_BE_OPEN_REVERSE = """\
DROP TRIGGER IF EXISTS candidacy_role_must_be_open ON candidacy;
"""

# A candidacy's stage, when it has one, belongs to the version pinned on the candidacy —
# the same "no cross-version reference" discipline as BriefStageCriterion in roles/0001.
CANDIDACY_STAGE_SAME_VERSION_FK = """\
ALTER TABLE candidacy
    ADD CONSTRAINT candidacy_stage_same_version
        FOREIGN KEY (brief_stage_id, brief_version_id)
        REFERENCES brief_stage (id, brief_version_id) DEFERRABLE INITIALLY DEFERRED;
"""

CANDIDACY_STAGE_SAME_VERSION_FK_REVERSE = """\
ALTER TABLE candidacy DROP CONSTRAINT IF EXISTS candidacy_stage_same_version;
"""

# ADR 0012: auto_close_at moves only in the same act that tells the candidate something,
# by exactly the fixed increment for that act. Deferred to commit, because the legitimate
# paths write the message and the deadline change as separate statements in one
# transaction (service functions in candidacies/services.py), in either order.
#
# The two paths need different message-existence checks, because they mean different
# things (see ADR 0012 and docs/backend-prd.md's enforcement map):
#   - A stage-transition reset (+90 days) rides on a message that was a PRECONDITION of
#     the transition, sent in an earlier, already-committed command — so this only checks
#     that a stage message exists at all, not that one arrived in this transaction.
#   - An extension (+30 days) IS itself the message — the text the recruiter writes is
#     what is sent — so this requires an extension message inserted in THIS transaction.
# sent_at comparison uses transaction_timestamp() (frozen at BEGIN), which is earlier than
# any application-computed timestamp written during the transaction; this is a same-wall-
# clock-window check appropriate to one recruiter's low-concurrency usage, not a
# cryptographic proof of atomicity.
AUTO_CLOSE_AT_MOVES_WITH_A_MESSAGE = """\
CREATE FUNCTION auto_close_at_moves_with_a_message() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
    reset_lo timestamptz := now() + interval '90 days' - interval '1 minute';
    reset_hi timestamptz := now() + interval '90 days' + interval '1 minute';
    is_reset boolean;
    is_extension boolean;
BEGIN
    IF NEW.auto_close_at = OLD.auto_close_at THEN
        RETURN NULL;
    END IF;
    IF NEW.closed_at IS NOT NULL THEN
        RAISE EXCEPTION 'a closed candidacy does not move' USING ERRCODE = '23514';
    END IF;

    is_reset := NEW.auto_close_at BETWEEN reset_lo AND reset_hi;
    is_extension := NEW.auto_close_at = OLD.auto_close_at + interval '30 days';

    IF is_reset THEN
        IF NOT EXISTS (
            SELECT 1 FROM candidate_message
            WHERE candidacy_id = NEW.id AND kind = 'stage'
        ) THEN
            RAISE EXCEPTION
                'the deadline resets on a stage transition, which requires a stage message on record'
                USING ERRCODE = '23514';
        END IF;
    ELSIF is_extension THEN
        IF NOT EXISTS (
            SELECT 1 FROM candidate_message
            WHERE candidacy_id = NEW.id AND kind = 'extension'
              AND sent_at >= transaction_timestamp()
        ) THEN
            RAISE EXCEPTION
                'an extension is itself a message, sent in the same transaction'
                USING ERRCODE = '23514';
        END IF;
    ELSE
        RAISE EXCEPTION
            'auto_close_at must move by exactly the reset (90 days) or extension (30 days) increment'
            USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END
$fn$;

CREATE CONSTRAINT TRIGGER auto_close_at_moves_with_a_message
    AFTER UPDATE OF auto_close_at ON candidacy
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION auto_close_at_moves_with_a_message();
"""

AUTO_CLOSE_AT_MOVES_WITH_A_MESSAGE_REVERSE = """\
DROP TRIGGER IF EXISTS auto_close_at_moves_with_a_message ON candidacy;
DROP FUNCTION IF EXISTS auto_close_at_moves_with_a_message();
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        ("organizations", "0001_initial"),
        ("people", "0001_initial"),
        ("roles", "0001_initial"),
        ("searches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidacy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "terminal_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("placed", "Placed"),
                            ("rejected", "Rejected"),
                            ("excluded", "Excluded"),
                            ("closed_no_response", "Closed No Response"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("auto_close_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidacies",
                        to="people.person",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidacies",
                        to="roles.role",
                    ),
                ),
                (
                    "brief_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.briefversion",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="channels.channel",
                    ),
                ),
                (
                    "brief_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.briefstage",
                    ),
                ),
            ],
            options={
                "db_table": "candidacy",
            },
            bases=(common.models.DerivesOrganization, models.Model),
        ),
        migrations.AddConstraint(
            model_name="candidacy",
            constraint=models.UniqueConstraint(
                fields=("role", "person"), name="candidacy_role_person_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidacy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("brief_stage__isnull", False), ("terminal_stage__isnull", True)),
                    models.Q(("brief_stage__isnull", True), ("terminal_stage__isnull", False)),
                    _connector="OR",
                ),
                name="candidacy_stage_xor_terminal",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidacy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("terminal_stage__isnull", True), ("closed_at__isnull", False), _connector="OR"
                ),
                name="candidacy_terminal_has_closed_at",
            ),
        ),
        migrations.CreateModel(
            name="CandidateMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("stage", "Stage"),
                            ("rejection", "Rejection"),
                            ("auto_closure", "Auto Closure"),
                            ("submission", "Submission"),
                            ("extension", "Extension"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("body", models.TextField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "candidacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="candidacies.candidacy",
                    ),
                ),
                (
                    "brief_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.briefstage",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "candidate_message",
            },
            bases=(common.models.DerivesOrganization, models.Model),
        ),
        migrations.AddConstraint(
            model_name="candidatemessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("body", ""), _negated=True),
                name="candidate_message_body_not_empty",
            ),
        ),
        migrations.RunSQL(CANDIDACY_ROLE_MUST_BE_OPEN, CANDIDACY_ROLE_MUST_BE_OPEN_REVERSE),
        migrations.RunSQL(CANDIDACY_STAGE_SAME_VERSION_FK, CANDIDACY_STAGE_SAME_VERSION_FK_REVERSE),
        migrations.RunSQL(
            AUTO_CLOSE_AT_MOVES_WITH_A_MESSAGE, AUTO_CLOSE_AT_MOVES_WITH_A_MESSAGE_REVERSE
        ),
        enable_rls("candidacy"),
        enable_rls("candidate_message"),
    ]
