# Generated by Django 5.2.17 on 2026-08-17 15:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from common.rls import enable_rls

# Invariant 1's attach gate, as a trigger: nothing attaches to a role that is not open.
# BEFORE INSERT, so it answers ahead of any column constraint. The function is shared —
# the candidacy table adds its own trigger over the same function in M4. A role invisible
# under RLS reads as no state at all, which also refuses; failing closed twice over.
ROLE_MUST_BE_OPEN = """\
CREATE FUNCTION role_must_be_open() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE role_state text;
BEGIN
    SELECT state INTO role_state FROM role WHERE id = NEW.role_id;
    IF role_state IS DISTINCT FROM 'open' THEN
        RAISE EXCEPTION 'role % is not open, so nothing can attach to it', NEW.role_id
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END
$fn$;

CREATE TRIGGER search_role_must_be_open
    BEFORE INSERT ON search
    FOR EACH ROW EXECUTE FUNCTION role_must_be_open();
"""

ROLE_MUST_BE_OPEN_REVERSE = """\
DROP TRIGGER IF EXISTS search_role_must_be_open ON search;
DROP FUNCTION IF EXISTS role_must_be_open();
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ran_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("coverage_note", models.TextField(blank=True, default="")),
                (
                    "brief_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.briefversion",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "ran_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="searches",
                        to="roles.role",
                    ),
                ),
                (
                    "sourcing_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="searches",
                        to="roles.sourcingscope",
                    ),
                ),
            ],
            options={
                "db_table": "search",
            },
        ),
        migrations.RunSQL(ROLE_MUST_BE_OPEN, ROLE_MUST_BE_OPEN_REVERSE),
        enable_rls("search"),
    ]
