# Generated by Django 5.2.17 on 2026-08-25 13:08

import common.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from common.rls import enable_rls

# A review's stage belongs to its own pinned version — the same "no cross-version
# reference" discipline as candidacy_stage_same_version (candidacies/migrations) and
# brief_stage_criterion (roles/migrations).
REVIEW_STAGE_SAME_VERSION_FK = """\
ALTER TABLE review
    ADD CONSTRAINT review_stage_same_version
        FOREIGN KEY (brief_stage_id, brief_version_id)
        REFERENCES brief_stage (id, brief_version_id) DEFERRABLE INITIALLY DEFERRED;
"""

REVIEW_STAGE_SAME_VERSION_FK_REVERSE = """\
ALTER TABLE review DROP CONSTRAINT IF EXISTS review_stage_same_version;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidacies", "0001_initial"),
        ("organizations", "0001_initial"),
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "brief_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.briefstage",
                    ),
                ),
                (
                    "brief_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.briefversion",
                    ),
                ),
                (
                    "candidacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="candidacies.candidacy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "review",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidacy", "brief_stage"), name="review_candidacy_stage_unique"
                    )
                ],
            },
            bases=(common.models.DerivesOrganization, models.Model),
        ),
        migrations.RunSQL(REVIEW_STAGE_SAME_VERSION_FK, REVIEW_STAGE_SAME_VERSION_FK_REVERSE),
        enable_rls("review"),
    ]
