# Generated by Django 5.2.17 on 2026-08-25 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models

from common.rls import enable_rls


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("outbound", "Outbound"),
                            ("inbound", "Inbound"),
                            ("referral", "Referral"),
                            ("network", "Network"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "channel",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["outbound", "inbound", "referral", "network"])
                        ),
                        name="channel_kind_valid",
                    )
                ],
            },
        ),
        enable_rls("channel"),
    ]
