# Generated by Django 5.2.17 on 2026-08-17 15:25

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from common.rls import enable_rls

# A criterion may only be assigned to a stage of its own Brief version. The join table
# carries brief_version_id redundantly so the database can hold that rule as two composite
# foreign keys — a cross-version assignment is then impossible, not merely validated.
SAME_VERSION_FKS = """\
ALTER TABLE criterion
    ADD CONSTRAINT criterion_id_version_unique UNIQUE (id, brief_version_id);
ALTER TABLE brief_stage
    ADD CONSTRAINT brief_stage_id_version_unique UNIQUE (id, brief_version_id);
ALTER TABLE brief_stage_criterion
    ADD CONSTRAINT bsc_stage_same_version
        FOREIGN KEY (brief_stage_id, brief_version_id)
        REFERENCES brief_stage (id, brief_version_id) DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT bsc_criterion_same_version
        FOREIGN KEY (criterion_id, brief_version_id)
        REFERENCES criterion (id, brief_version_id) DEFERRABLE INITIALLY DEFERRED;
"""

SAME_VERSION_FKS_REVERSE = """\
ALTER TABLE brief_stage_criterion
    DROP CONSTRAINT IF EXISTS bsc_stage_same_version,
    DROP CONSTRAINT IF EXISTS bsc_criterion_same_version;
ALTER TABLE brief_stage DROP CONSTRAINT IF EXISTS brief_stage_id_version_unique;
ALTER TABLE criterion DROP CONSTRAINT IF EXISTS criterion_id_version_unique;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brief",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "brief",
            },
        ),
        migrations.CreateModel(
            name="BriefVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="roles.brief",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "brief_version",
            },
        ),
        migrations.CreateModel(
            name="BriefStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=120)),
                ("purpose", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.CharField(
                        choices=[("recruiter", "Recruiter"), ("client", "Client")],
                        default="recruiter",
                        max_length=10,
                    ),
                ),
                ("candidate_message", models.TextField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "brief_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="roles.briefversion",
                    ),
                ),
            ],
            options={
                "db_table": "brief_stage",
            },
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("cell_label", models.CharField(blank=True, default="", max_length=80)),
                (
                    "brief_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="roles.briefversion",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "criterion",
            },
        ),
        migrations.CreateModel(
            name="BriefStageCriterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "brief_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_assignments",
                        to="roles.briefstage",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "brief_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="roles.briefversion",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="roles.criterion",
                    ),
                ),
            ],
            options={
                "db_table": "brief_stage_criterion",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_reason", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="clients.client",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "pinned_brief_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.briefversion",
                    ),
                ),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.AddField(
            model_name="brief",
            name="role",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brief",
                to="roles.role",
            ),
        ),
        migrations.CreateModel(
            name="SourcingScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "markets",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "employers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("geography", models.TextField(blank=True, default="")),
                (
                    "exclusions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "brief_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scopes",
                        to="roles.briefversion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "sourcing_scope",
            },
        ),
        migrations.AddConstraint(
            model_name="briefversion",
            constraint=models.UniqueConstraint(
                fields=("brief", "version"), name="brief_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="briefstage",
            constraint=models.UniqueConstraint(
                fields=("brief_version", "position"), name="brief_stage_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="briefstage",
            constraint=models.CheckConstraint(
                condition=models.Q(("candidate_message", ""), _negated=True),
                name="brief_stage_message_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="briefstage",
            constraint=models.CheckConstraint(
                condition=models.Q(("owner__in", ["recruiter", "client"])),
                name="brief_stage_owner_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.UniqueConstraint(
                fields=("brief_version", "position"), name="criterion_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="briefstagecriterion",
            constraint=models.UniqueConstraint(
                fields=("brief_stage", "criterion"), name="brief_stage_criterion_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["draft", "open", "closed"])),
                name="role_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "open"), _negated=True),
                    models.Q(
                        ("pinned_brief_version__isnull", False),
                        ("opened_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="role_open_is_pinned",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "closed"), _negated=True),
                    ("closed_at__isnull", False),
                    _connector="OR",
                ),
                name="role_closed_has_closed_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcingscope",
            constraint=models.UniqueConstraint(
                fields=("brief_version", "revision"),
                name="sourcing_scope_revision_unique",
            ),
        ),
        migrations.RunSQL(SAME_VERSION_FKS, SAME_VERSION_FKS_REVERSE),
        enable_rls("role"),
        enable_rls("brief"),
        enable_rls("brief_version"),
        enable_rls("criterion"),
        enable_rls("brief_stage"),
        enable_rls("brief_stage_criterion"),
        enable_rls("sourcing_scope"),
    ]
