# Generated by Django 5.2.17 on 2026-08-25 13:08, then hand-merged from a two-file split
# (reviews is a new app in the same generation pass, deferring the cross-app FK to a
# second migration) and extended with RLS, the append-only revoke, and the composite
# uniqueness findings/migrations composite-FKs onto.

import common.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

from common.rls import enable_rls

# Invariant 8: Evidence is append-only. UPDATE and DELETE are revoked from rcp_app — a
# permission grant, not a UI convention.
REVOKE_MUTATION = "REVOKE UPDATE, DELETE ON evidence FROM rcp_app;"
REVOKE_MUTATION_REVERSE = "GRANT UPDATE, DELETE ON evidence TO rcp_app;"

# id is already unique (it is the primary key), so (id, review_id, criterion_id) is
# trivially unique too — this is purely so findings/migrations can add a composite FK
# on (evidence_id, review_id, criterion_id), guaranteeing a Finding's evidence always
# belongs to the Finding's own (review, criterion) pair, never someone else's.
EVIDENCE_ID_REVIEW_CRITERION_UNIQUE = """\
ALTER TABLE evidence
    ADD CONSTRAINT evidence_id_review_criterion_unique UNIQUE (id, review_id, criterion_id);
"""

EVIDENCE_ID_REVIEW_CRITERION_UNIQUE_REVERSE = """\
ALTER TABLE evidence DROP CONSTRAINT IF EXISTS evidence_id_review_criterion_unique;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("organizations", "0001_initial"),
        ("reviews", "0001_initial"),
        ("roles", "0001_initial"),
        ("sightings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("char_start", models.IntegerField(blank=True, null=True)),
                ("char_end", models.IntegerField(blank=True, null=True)),
                ("page", models.IntegerField(blank=True, null=True)),
                ("paragraph", models.IntegerField(blank=True, null=True)),
                ("quote", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.criterion",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reviews.review",
                    ),
                ),
                (
                    "sighting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sightings.sighting",
                    ),
                ),
            ],
            options={
                "db_table": "evidence",
            },
            bases=(common.models.DerivesOrganization, models.Model),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.UniqueConstraint(
                fields=("review", "criterion"), name="evidence_review_criterion_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("char_end__isnull", False),
                        ("char_start__isnull", False),
                        ("document__isnull", False),
                        ("page__isnull", False),
                        ("paragraph__isnull", False),
                        ("quote__isnull", False),
                        ("sighting__isnull", True),
                    ),
                    models.Q(
                        ("char_end__isnull", False),
                        ("char_start__isnull", False),
                        ("document__isnull", True),
                        ("quote__isnull", False),
                        ("sighting__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="evidence_points_at_document_or_sighting",
            ),
        ),
        migrations.RunSQL(
            EVIDENCE_ID_REVIEW_CRITERION_UNIQUE, EVIDENCE_ID_REVIEW_CRITERION_UNIQUE_REVERSE
        ),
        enable_rls("evidence"),
        migrations.RunSQL(REVOKE_MUTATION, REVOKE_MUTATION_REVERSE),
    ]
