# Generated by Django 5.2.17 on 2026-08-17 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models

from common.rls import enable_rls


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=300)),
                ("headline", models.CharField(blank=True, default="", max_length=300)),
                (
                    "current_employer",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("location", models.CharField(blank=True, default="", max_length=300)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "person",
            },
        ),
        enable_rls("person"),
    ]
