# Generated by Django 5.2.17 on 2026-08-25 12:44

import common.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from common.rls import enable_rls

# Invariant 8: DecisionEvent is append-only. UPDATE and DELETE are revoked from rcp_app —
# a permission grant, not a UI convention — matching the pattern the invariant test
# expects for evidence and submission_record once those tables exist (M5, M6).
REVOKE_MUTATION = "REVOKE UPDATE, DELETE ON decision_event FROM rcp_app;"
REVOKE_MUTATION_REVERSE = "GRANT UPDATE, DELETE ON decision_event TO rcp_app;"


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidacies", "0001_initial"),
        ("organizations", "0001_initial"),
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("reject", "Reject")], default="reject", max_length=10
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("below_criteria", "Below Criteria"),
                            ("salary_expectation", "Salary Expectation"),
                            ("location", "Location"),
                            ("withdrew", "Withdrew"),
                            ("counter_offer", "Counter Offer"),
                            ("client_declined", "Client Declined"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reason_text", models.TextField()),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "candidacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="candidacies.candidacy",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "decision",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind", "reject")), name="decision_kind_valid"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "reason_code__in",
                                [
                                    "below_criteria",
                                    "salary_expectation",
                                    "location",
                                    "withdrew",
                                    "counter_offer",
                                    "client_declined",
                                ],
                            )
                        ),
                        name="decision_reason_code_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason_text", ""), _negated=True),
                        name="decision_reason_text_not_empty",
                    ),
                ],
            },
            bases=(common.models.DerivesOrganization, models.Model),
        ),
        migrations.CreateModel(
            name="DecisionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("candidacy_created", "Candidacy Created"),
                            ("stage_changed", "Stage Changed"),
                            ("review_recorded", "Review Recorded"),
                            ("finding_recorded", "Finding Recorded"),
                            ("signal_resolved", "Signal Resolved"),
                            ("signal_overridden", "Signal Overridden"),
                            ("rejected", "Rejected"),
                            ("excluded", "Excluded"),
                            ("submission_created", "Submission Created"),
                            ("message_sent", "Message Sent"),
                            ("deadline_extended", "Deadline Extended"),
                            ("checkpoint_recorded", "Checkpoint Recorded"),
                            ("auto_closed", "Auto Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("summary", models.TextField()),
                (
                    "terminal_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("placed", "Placed"),
                            ("rejected", "Rejected"),
                            ("excluded", "Excluded"),
                            ("closed_no_response", "Closed No Response"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "brief_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.briefstage",
                    ),
                ),
                (
                    "candidacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="candidacies.candidacy",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "decision_event",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type__in",
                                [
                                    "candidacy_created",
                                    "stage_changed",
                                    "review_recorded",
                                    "finding_recorded",
                                    "signal_resolved",
                                    "signal_overridden",
                                    "rejected",
                                    "excluded",
                                    "submission_created",
                                    "message_sent",
                                    "deadline_extended",
                                    "checkpoint_recorded",
                                    "auto_closed",
                                ],
                            )
                        ),
                        name="decision_event_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("brief_stage__isnull", False),
                            ("terminal_stage__isnull", False),
                            _negated=True,
                        ),
                        name="decision_event_stage_not_both",
                    ),
                ],
            },
            bases=(common.models.DerivesOrganization, models.Model),
        ),
        enable_rls("decision"),
        enable_rls("decision_event"),
        migrations.RunSQL(REVOKE_MUTATION, REVOKE_MUTATION_REVERSE),
    ]
