# Generated by Django 5.2.17 on 2026-08-25 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidacies", "0001_initial"),
        ("decisions", "0001_initial"),
        ("organizations", "0001_initial"),
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="decisionevent",
            name="decision_event_type_valid",
        ),
        migrations.AlterField(
            model_name="decisionevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("candidacy_created", "Candidacy Created"),
                    ("stage_changed", "Stage Changed"),
                    ("review_recorded", "Review Recorded"),
                    ("finding_recorded", "Finding Recorded"),
                    ("signal_resolved", "Signal Resolved"),
                    ("signal_overridden", "Signal Overridden"),
                    ("rejected", "Rejected"),
                    ("excluded", "Excluded"),
                    ("submission_created", "Submission Created"),
                    ("message_sent", "Message Sent"),
                    ("deadline_extended", "Deadline Extended"),
                    ("checkpoint_recorded", "Checkpoint Recorded"),
                    ("auto_closed", "Auto Closed"),
                    ("placed", "Placed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="decisionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "candidacy_created",
                            "stage_changed",
                            "review_recorded",
                            "finding_recorded",
                            "signal_resolved",
                            "signal_overridden",
                            "rejected",
                            "excluded",
                            "submission_created",
                            "message_sent",
                            "deadline_extended",
                            "checkpoint_recorded",
                            "auto_closed",
                            "placed",
                        ],
                    )
                ),
                name="decision_event_type_valid",
            ),
        ),
    ]
