# Generated by Django 5.2.17 on 2026-08-25 13:23

import django.db.models.deletion
import django.utils.timezone
import submissions.models
import uuid
from django.conf import settings
from django.db import migrations, models

from common.rls import enable_rls

# Invariant 8: SubmissionRecord is append-only. UPDATE and DELETE are revoked from
# rcp_app — a permission grant, not a UI convention.
REVOKE_MUTATION = "REVOKE UPDATE, DELETE ON submission_record FROM rcp_app;"
REVOKE_MUTATION_REVERSE = "GRANT UPDATE, DELETE ON submission_record TO rcp_app;"

# Invariant 5's stated enforcement: "database trigger on submission insert." The
# application-level check in submissions/services.py is what a request actually hits —
# this is the backstop for any insert that reaches the table by another path.
NO_UNRESOLVED_SIGNAL_TRIGGER = """\
CREATE FUNCTION no_unresolved_crosscheck_signal() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
    IF EXISTS (
        SELECT 1 FROM crosscheck_signal
        WHERE candidacy_id = NEW.candidacy_id AND resolution_kind IS NULL
    ) THEN
        RAISE EXCEPTION 'candidacy % has unresolved crosscheck signals', NEW.candidacy_id
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END
$fn$;

CREATE TRIGGER submission_requires_resolved_signals
    BEFORE INSERT ON submission_record
    FOR EACH ROW EXECUTE FUNCTION no_unresolved_crosscheck_signal();
"""

NO_UNRESOLVED_SIGNAL_TRIGGER_REVERSE = """\
DROP TRIGGER IF EXISTS submission_requires_resolved_signals ON submission_record;
DROP FUNCTION IF EXISTS no_unresolved_crosscheck_signal();
"""

# ADR 0017, the third and last named entry in ADR 0014's register of definer crossings.
# The candidate has no session and no org — the token is the only credential — so this
# is the one query in the whole product that legitimately reads across the tenancy
# boundary without one. Scoped tightly: exactly one submission's snapshot, its
# candidacy's open/closed state, the org's AI-use notice text, and that candidacy's
# messages. Nothing else is reachable through it.
CANDIDATE_VIEW_BY_TOKEN = """\
CREATE FUNCTION candidate_view_by_token(token text) RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $fn$
    SELECT jsonb_build_object(
        'reference', sr.reference,
        'signed_off_at', sr.signed_off_at,
        'snapshot', sr.snapshot,
        'auto_close_at', c.auto_close_at,
        'closed_at', c.closed_at,
        'ai_notice', o.ai_notice_template,
        'messages', COALESCE((
            SELECT jsonb_agg(
                jsonb_build_object('kind', cm.kind, 'sent_at', cm.sent_at, 'body', cm.body)
                ORDER BY cm.sent_at
            )
            FROM candidate_message cm
            WHERE cm.candidacy_id = sr.candidacy_id
        ), '[]'::jsonb)
    )
    FROM submission_record sr
    JOIN candidacy c ON c.id = sr.candidacy_id
    JOIN organization o ON o.id = sr.organization_id
    WHERE sr.candidate_link_id = token
$fn$;

GRANT SELECT ON submission_record, candidacy, organization, candidate_message TO rcp_login;
GRANT CREATE ON SCHEMA public TO rcp_login;
ALTER FUNCTION candidate_view_by_token(text) OWNER TO rcp_login;
REVOKE CREATE ON SCHEMA public FROM rcp_login;
REVOKE ALL ON FUNCTION candidate_view_by_token(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION candidate_view_by_token(text) TO rcp_app;
"""

CANDIDATE_VIEW_BY_TOKEN_REVERSE = "DROP FUNCTION IF EXISTS candidate_view_by_token(text);"


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidacies", "0001_initial"),
        ("crosscheck", "0001_initial"),
        ("organizations", "0001_initial"),
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("signed_off_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reference", models.CharField(max_length=40, unique=True)),
                (
                    "candidate_link_id",
                    models.CharField(
                        default=submissions.models._candidate_link_id, max_length=64, unique=True
                    ),
                ),
                ("snapshot", models.JSONField()),
                (
                    "brief_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.briefversion",
                    ),
                ),
                (
                    "candidacy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission_record",
                        to="candidacies.candidacy",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "signed_off_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submission_record",
            },
        ),
        enable_rls("submission_record"),
        migrations.RunSQL(REVOKE_MUTATION, REVOKE_MUTATION_REVERSE),
        migrations.RunSQL(NO_UNRESOLVED_SIGNAL_TRIGGER, NO_UNRESOLVED_SIGNAL_TRIGGER_REVERSE),
        migrations.RunSQL(CANDIDATE_VIEW_BY_TOKEN, CANDIDATE_VIEW_BY_TOKEN_REVERSE),
    ]
