# Generated by Django 5.2.17 on 2026-08-25 13:08, then hand-merged from a two-file split
# (reviews is a new app in the same generation pass, deferring the cross-app FK to a
# second migration) and extended with the same-(review, criterion) composite FK onto
# evidence, and RLS.

import common.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from common.rls import enable_rls

# A Finding can only back onto Evidence scoped to its own (review, criterion) pair —
# never a citation that actually belongs to a different review or a different
# criterion. Evidence exposes (id, review_id, criterion_id) as a unique triple
# (evidence/migrations) precisely so this composite FK can exist. NULL-safe by MATCH
# SIMPLE: a not_found Finding has evidence_id NULL, and the constraint does not fire.
FINDING_EVIDENCE_SAME_REVIEW_CRITERION_FK = """\
ALTER TABLE finding
    ADD CONSTRAINT finding_evidence_same_review_criterion
        FOREIGN KEY (evidence_id, review_id, criterion_id)
        REFERENCES evidence (id, review_id, criterion_id) DEFERRABLE INITIALLY DEFERRED;
"""

FINDING_EVIDENCE_SAME_REVIEW_CRITERION_FK_REVERSE = """\
ALTER TABLE finding DROP CONSTRAINT IF EXISTS finding_evidence_same_review_criterion;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("evidence", "0001_initial"),
        ("organizations", "0001_initial"),
        ("reviews", "0001_initial"),
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("evidenced", "Evidenced"), ("not_found", "Not Found")],
                        max_length=10,
                    ),
                ),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.criterion",
                    ),
                ),
                (
                    "evidence",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finding",
                        to="evidence.evidence",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "db_table": "finding",
            },
            bases=(common.models.DerivesOrganization, models.Model),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("review", "criterion"), name="finding_review_criterion_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["evidenced", "not_found"])),
                name="finding_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "evidenced"), _negated=True),
                    ("evidence__isnull", False),
                    _connector="OR",
                ),
                name="finding_evidenced_requires_evidence",
            ),
        ),
        migrations.RunSQL(
            FINDING_EVIDENCE_SAME_REVIEW_CRITERION_FK,
            FINDING_EVIDENCE_SAME_REVIEW_CRITERION_FK_REVERSE,
        ),
        enable_rls("finding"),
    ]
