# Generated by Django 5.2.17 on 2026-08-17 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models

from common.rls import enable_rls

# Invariant 9: a person cannot exist without at least one resolving sighting. The trigger
# is INITIALLY IMMEDIATE, so a bare INSERT on person refuses at the statement — a skill can
# ask an agent not to invent a person; this refuses the write. The legitimate creation path
# runs SET CONSTRAINTS person_provenance DEFERRED and inserts person then sighting in one
# transaction; the check then runs at commit, where it is true.
#
# The function is SECURITY DEFINER, owned by rcp_login, and scoped by NEW.organization_id:
# an integrity check must not depend on the caller's org context, because deferred events
# can fire after the context has moved on — the fact being checked belongs to the row, not
# to whoever happens to commit. A definer crossing, recorded in ADR 0014's register.
PERSON_PROVENANCE = """\
CREATE FUNCTION person_has_resolving_sighting() RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM sighting
        WHERE person_id = NEW.id
          AND organization_id = NEW.organization_id
          AND resolving
    ) THEN
        RAISE EXCEPTION 'person % has no resolving sighting', NEW.id
            USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END
$fn$;

GRANT SELECT ON sighting TO rcp_login;
GRANT CREATE ON SCHEMA public TO rcp_login;
ALTER FUNCTION person_has_resolving_sighting() OWNER TO rcp_login;
REVOKE CREATE ON SCHEMA public FROM rcp_login;
REVOKE ALL ON FUNCTION person_has_resolving_sighting() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION person_has_resolving_sighting() TO rcp_owner, rcp_app;

CREATE CONSTRAINT TRIGGER person_provenance
    AFTER INSERT ON person
    DEFERRABLE INITIALLY IMMEDIATE
    FOR EACH ROW EXECUTE FUNCTION person_has_resolving_sighting();
"""

PERSON_PROVENANCE_REVERSE = """\
DROP TRIGGER IF EXISTS person_provenance ON person;
DROP FUNCTION IF EXISTS person_has_resolving_sighting();
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("people", "0001_initial"),
        ("searches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sighting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_url", models.TextField()),
                (
                    "source_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "source_kind",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("retrieved_at", models.DateTimeField()),
                ("snapshot_excerpt", models.TextField(blank=True, default="")),
                ("resolving", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sightings",
                        to="people.person",
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sightings",
                        to="searches.search",
                    ),
                ),
            ],
            options={
                "db_table": "sighting",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("source_url", ""), _negated=True),
                        name="sighting_has_source_url",
                    )
                ],
            },
        ),
        migrations.RunSQL(PERSON_PROVENANCE, PERSON_PROVENANCE_REVERSE),
        enable_rls("sighting"),
    ]
