# Generated by Django 5.2.17 on 2026-08-25 13:23

import common.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from common.rls import enable_rls


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidacies", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrosscheckSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("timeline_overlap", "Timeline Overlap"),
                            ("contact_collision", "Contact Collision"),
                            ("document_author", "Document Author"),
                            ("duplicate_candidacy", "Duplicate Candidacy"),
                        ],
                        max_length=30,
                    ),
                ),
                ("detail", models.TextField()),
                ("artifact", models.JSONField()),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resolution_kind",
                    models.CharField(
                        blank=True,
                        choices=[("resolved", "Resolved"), ("overridden", "Overridden")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, null=True)),
                (
                    "candidacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crosscheck_signals",
                        to="candidacies.candidacy",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crosscheck_signal",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type__in",
                                [
                                    "timeline_overlap",
                                    "contact_collision",
                                    "document_author",
                                    "duplicate_candidacy",
                                ],
                            )
                        ),
                        name="crosscheck_signal_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("resolution_kind__isnull", True),
                                ("resolved_by__isnull", True),
                                ("resolved_at__isnull", True),
                                ("resolution_note__isnull", True),
                            ),
                            models.Q(
                                ("resolution_kind__in", ["resolved", "overridden"]),
                                ("resolved_by__isnull", False),
                                ("resolved_at__isnull", False),
                                models.Q(("resolution_note", ""), _negated=True),
                                ("resolution_note__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="crosscheck_signal_resolution_complete_or_absent",
                    ),
                ],
            },
            bases=(common.models.DerivesOrganization, models.Model),
        ),
        enable_rls("crosscheck_signal"),
    ]
