# Generated by Django 5.2.17 on 2026-08-25 13:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

from common.rls import enable_rls


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(default="cv", max_length=20)),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("filename", models.CharField(max_length=300)),
                ("sha256", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("parsed_text", models.TextField()),
                ("pages", models.JSONField(default=list)),
                ("paragraphs", models.JSONField(default=list)),
                ("author", models.CharField(blank=True, default="", max_length=300)),
                ("producer", models.CharField(blank=True, default="", max_length=300)),
                ("properties_created", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "document",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind", "cv")), name="document_kind_valid"
                    )
                ],
            },
        ),
        enable_rls("document"),
    ]
