# Generated by Django 5.2.17 on 2026-08-25 13:23

import common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from common.rls import enable_rls


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidacies", "0001_initial"),
        ("organizations", "0001_initial"),
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("started_on", models.DateField()),
                ("probation_ends_on", models.DateField()),
                (
                    "brief_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="roles.briefversion",
                    ),
                ),
                (
                    "candidacy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placement",
                        to="candidacies.candidacy",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "placement",
            },
            bases=(common.models.DerivesOrganization, models.Model),
        ),
        migrations.CreateModel(
            name="PlacementCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[(7, "Seven"), (30, "Thirty"), (60, "Sixty"), (90, "Ninety")]
                    ),
                ),
                ("due_on", models.DateField()),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("brief_feedback", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="placements.placement",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "placement_checkpoint",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("placement", "day"), name="checkpoint_placement_day_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("day__in", [7, 30, 60, 90])),
                        name="checkpoint_day_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("recorded_at__isnull", True),
                                ("recorded_by__isnull", True),
                                ("note__isnull", True),
                            ),
                            models.Q(
                                ("recorded_at__isnull", False),
                                ("recorded_by__isnull", False),
                                ("note__isnull", False),
                                models.Q(("note", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="checkpoint_recorded_complete_or_absent",
                    ),
                ],
            },
            bases=(common.models.DerivesOrganization, models.Model),
        ),
        enable_rls("placement"),
        enable_rls("placement_checkpoint"),
    ]
